# Some Random tests and experiments


In [12]:
import numpy as np
import math

In [21]:
func = lambda ele: math.ceil(abs(ele))
toInt = np.vectorize(func)

In [22]:
arr1 = np.random.randn(1,5)
arr1 = toInt(arr1)
arr1

array([[1, 1, 1, 2, 2]])

In [23]:
arr2 = np.random.randn(1,5)
arr2 = toInt(arr1)
arr2

array([[1, 1, 1, 2, 2]])

In [24]:
arr1*arr2

array([[1, 1, 1, 4, 4]])

In [26]:
arr1 @ arr2.reshape((-1,1))

array([[11]])

In [31]:
q=np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
q.shape

(3, 4)

In [34]:
p = np.array([[1],
              [2],
              [3],
              [4]])
p.shape

(4, 1)

In [37]:
q@p

array([[49],
       [16],
       [15]])